/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.simm.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SimHomepageActivityBin generated by hbm2java
 */
@Entity
@Table(name="sim_homepage_activity_bin"
)
public class SimHomepageActivityBin  implements java.io.Serializable {


     private String id;
     private SimHomepageActivity activityId;
     private int binOrder;
     private byte[] binData;
     private long createdOn;

    public SimHomepageActivityBin() {
    }


    public SimHomepageActivityBin(SimHomepageActivity activityId, int binOrder, long createdOn) {
        this.activityId = activityId;
        this.binOrder = binOrder;
        this.createdOn = createdOn;
    }
    public SimHomepageActivityBin(SimHomepageActivity activityId, int binOrder, byte[] binData, long createdOn) {
       this.activityId = activityId;
       this.binOrder = binOrder;
       this.binData = binData;
       this.createdOn = createdOn;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="activity_id", nullable=false)
		public SimHomepageActivity getActivityId() {
			return this.activityId;
		}

    public void setActivityId(SimHomepageActivity activityId) {
        this.activityId = activityId;
    }

    @Column(name="bin_order", nullable=false)
		public int getBinOrder() {
			return this.binOrder;
		}

    public void setBinOrder(int binOrder) {
        this.binOrder = binOrder;
    }

    @Column(name="bin_data")
		public byte[] getBinData() {
			return this.binData;
		}

    public void setBinData(byte[] binData) {
        this.binData = binData;
    }

    @Column(name="created_on", nullable=false)
		public long getCreatedOn() {
			return this.createdOn;
		}

    public void setCreatedOn(long createdOn) {
        this.createdOn = createdOn;
    }




}


