/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.simm.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SimNotification generated by hbm2java
 */
@Entity
@Table(name="sim_notification"
)
public class SimNotification  implements java.io.Serializable {


     private String id;
     private String title;
     private String description;
     private String toUserId;
     private byte status;
     private String fromUserId;
     private String link;
     private long createdOn;
     private String notfType;
     private String notfIcon;

    public SimNotification() {
    }


    public SimNotification(String toUserId, byte status, String fromUserId, long createdOn) {
        this.toUserId = toUserId;
        this.status = status;
        this.fromUserId = fromUserId;
        this.createdOn = createdOn;
    }
    public SimNotification(String title, String description, String toUserId, byte status, String fromUserId, String link, long createdOn, String notfType, String notfIcon) {
       this.title = title;
       this.description = description;
       this.toUserId = toUserId;
       this.status = status;
       this.fromUserId = fromUserId;
       this.link = link;
       this.createdOn = createdOn;
       this.notfType = notfType;
       this.notfIcon = notfIcon;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }

    @Column(name="title", length=512)
		public String getTitle() {
			return this.title;
		}

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name="description", length=65535)
		public String getDescription() {
			return this.description;
		}

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="to_user_id", nullable=false, length=36)
		public String getToUserId() {
			return this.toUserId;
		}

    public void setToUserId(String toUserId) {
        this.toUserId = toUserId;
    }

    @Column(name="status", nullable=false)
		public byte getStatus() {
			return this.status;
		}

    public void setStatus(byte status) {
        this.status = status;
    }

    @Column(name="from_user_id", nullable=false, length=36)
		public String getFromUserId() {
			return this.fromUserId;
		}

    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId;
    }

    @Column(name="link", length=512)
		public String getLink() {
			return this.link;
		}

    public void setLink(String link) {
        this.link = link;
    }

    @Column(name="created_on", nullable=false)
		public long getCreatedOn() {
			return this.createdOn;
		}

    public void setCreatedOn(long createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name="notf_type")
		public String getNotfType() {
			return this.notfType;
		}

    public void setNotfType(String notfType) {
        this.notfType = notfType;
    }

    @Column(name="notf_icon", length=512)
		public String getNotfIcon() {
			return this.notfIcon;
		}

    public void setNotfIcon(String notfIcon) {
        this.notfIcon = notfIcon;
    }




}


