/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.calendar.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CalCalendar generated by hbm2java
 */
@Entity
@Table(name="cal_calendar"
)
public class CalCalendar  implements java.io.Serializable {


     private String id;
     private long createdOn;
     private String ownerId;
     private long lastModifiedOn;
     private String lastModifiedBy;
     private boolean active;
     private Set<CalItem> calItems = new HashSet<CalItem>(0);

    public CalCalendar() {
    }


    public CalCalendar(long createdOn, String ownerId, long lastModifiedOn, String lastModifiedBy, boolean active) {
        this.createdOn = createdOn;
        this.ownerId = ownerId;
        this.lastModifiedOn = lastModifiedOn;
        this.lastModifiedBy = lastModifiedBy;
        this.active = active;
    }
    public CalCalendar(long createdOn, String ownerId, long lastModifiedOn, String lastModifiedBy, boolean active, Set<CalItem> calItems) {
       this.createdOn = createdOn;
       this.ownerId = ownerId;
       this.lastModifiedOn = lastModifiedOn;
       this.lastModifiedBy = lastModifiedBy;
       this.active = active;
       this.calItems = calItems;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }

    @Column(name="created_on", nullable=false)
		public long getCreatedOn() {
			return this.createdOn;
		}

    public void setCreatedOn(long createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name="owner_id", nullable=false, length=36)
		public String getOwnerId() {
			return this.ownerId;
		}

    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    @Column(name="last_modified_on", nullable=false)
		public long getLastModifiedOn() {
			return this.lastModifiedOn;
		}

    public void setLastModifiedOn(long lastModifiedOn) {
        this.lastModifiedOn = lastModifiedOn;
    }

    @Column(name="last_modified_by", nullable=false, length=36)
		public String getLastModifiedBy() {
			return this.lastModifiedBy;
		}

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @Column(name="active", nullable=false)
		public boolean isActive() {
			return this.active;
		}

    public void setActive(boolean active) {
        this.active = active;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="calendarId")
		public Set<CalItem> getCalItems() {
			return this.calItems;
		}

    public void setCalItems(Set<CalItem> calItems) {
        this.calItems = calItems;
    }




}


