/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.chatim.impl.model;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChaRooms generated by hbm2java
 */
@Entity
@Table(name = "cha_rooms")
public class ChaRooms implements java.io.Serializable {

	private String id;
	private String title;
	private long createdOn;
	private String createdBy;
	private String groupId;
	private Set<ChaProperties> chaPropertieses = new HashSet<ChaProperties>(0);
	private Set<ChaRoomHasMessages> chaRoomHasMessageses = new HashSet<ChaRoomHasMessages>(
			0);
	private Set<ChaWordFilter> chaWordFilters = new HashSet<ChaWordFilter>(0);
	private Set<ChaRoomHasParticipants> chaRoomHasParticipantses = new HashSet<ChaRoomHasParticipants>(
			0);
	private Set<ChaActionOnUser> chaActionOnUsers = new HashSet<ChaActionOnUser>(
			0);

	public ChaRooms() {
	}

	public ChaRooms(String title, long createdOn, String createdBy) {
		this.title = title;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public ChaRooms(String title, long createdOn, String createdBy,
			String groupId, Set<ChaProperties> chaPropertieses,
			Set<ChaRoomHasMessages> chaRoomHasMessageses,
			Set<ChaWordFilter> chaWordFilters,
			Set<ChaRoomHasParticipants> chaRoomHasParticipantses,
			Set<ChaActionOnUser> chaActionOnUsers) {
		this.title = title;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.groupId = groupId;
		this.chaPropertieses = chaPropertieses;
		this.chaRoomHasMessageses = chaRoomHasMessageses;
		this.chaWordFilters = chaWordFilters;
		this.chaRoomHasParticipantses = chaRoomHasParticipantses;
		this.chaActionOnUsers = chaActionOnUsers;
	}

	@Id
	public String getId() {
		if (this.id == null) {
			this.id = java.util.UUID.randomUUID().toString();
		}

		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 512)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "created_on", nullable = false)
	public long getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(long createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", nullable = false, length = 36)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "group_id", length = 36)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomId")
	public Set<ChaProperties> getChaPropertieses() {
		return this.chaPropertieses;
	}

	public void setChaPropertieses(Set<ChaProperties> chaPropertieses) {
		this.chaPropertieses = chaPropertieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomId")
	public Set<ChaRoomHasMessages> getChaRoomHasMessageses() {
		return this.chaRoomHasMessageses;
	}

	public void setChaRoomHasMessageses(
			Set<ChaRoomHasMessages> chaRoomHasMessageses) {
		this.chaRoomHasMessageses = chaRoomHasMessageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomId")
	public Set<ChaWordFilter> getChaWordFilters() {
		return this.chaWordFilters;
	}

	public void setChaWordFilters(Set<ChaWordFilter> chaWordFilters) {
		this.chaWordFilters = chaWordFilters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomId")
	public Set<ChaRoomHasParticipants> getChaRoomHasParticipantses() {
		return this.chaRoomHasParticipantses;
	}

	public void setChaRoomHasParticipantses(
			Set<ChaRoomHasParticipants> chaRoomHasParticipantses) {
		this.chaRoomHasParticipantses = chaRoomHasParticipantses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomId")
	public Set<ChaActionOnUser> getChaActionOnUsers() {
		return this.chaActionOnUsers;
	}

	public void setChaActionOnUsers(Set<ChaActionOnUser> chaActionOnUsers) {
		this.chaActionOnUsers = chaActionOnUsers;
	}

}
