/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.chatim.impl.model;

// Generated by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChaRoomHasParticipants generated by hbm2java
 */
@Entity
@Table(name = "cha_room_has_participants")
public class ChaRoomHasParticipants implements java.io.Serializable {

	private String id;
	private ChaRooms roomId;
	private String userId;
	private long joinedOn;

	public ChaRoomHasParticipants() {
	}

	public ChaRoomHasParticipants(ChaRooms roomId, String userId, long joinedOn) {
		this.roomId = roomId;
		this.userId = userId;
		this.joinedOn = joinedOn;
	}

	@Id
	public String getId() {
		if (this.id == null) {
			this.id = java.util.UUID.randomUUID().toString();
		}

		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	public ChaRooms getRoomId() {
		return this.roomId;
	}

	public void setRoomId(ChaRooms roomId) {
		this.roomId = roomId;
	}

	@Column(name = "user_id", nullable = false, length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "joined_on", nullable = false)
	public long getJoinedOn() {
		return this.joinedOn;
	}

	public void setJoinedOn(long joinedOn) {
		this.joinedOn = joinedOn;
	}

}
