/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.componentlibrary.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApiGadget generated by hbm2java
 */
@Entity
@Table(name="cmp_gadget"
)
public class ApiGadget  implements java.io.Serializable {


     private String id;
     private String title;
     private String description;
     private String author;
     private String infoLink;
     private String boxLink;
     private String pageLink;
     private long registeredOn;
     private String iconLink;
     private String owner;
     private boolean enabled;
     private String configPage;
     private String privateKey;
     private Set<ApiGadgetHasUser> apiGadgetHasUsers = new HashSet<ApiGadgetHasUser>(0);
     private Set<ApiGadgetHasPermission> apiGadgetHasPermissions = new HashSet<ApiGadgetHasPermission>(0);

    public ApiGadget() {
    }


    public ApiGadget(String title, String boxLink, long registeredOn, String owner, boolean enabled, String privateKey) {
        this.title = title;
        this.boxLink = boxLink;
        this.registeredOn = registeredOn;
        this.owner = owner;
        this.enabled = enabled;
        this.privateKey = privateKey;
    }
    public ApiGadget(String title, String description, String author, String infoLink, String boxLink, String pageLink, long registeredOn, String iconLink, String owner, boolean enabled, String configPage, String privateKey, Set<ApiGadgetHasUser> apiGadgetHasUsers, Set<ApiGadgetHasPermission> apiGadgetHasPermissions) {
       this.title = title;
       this.description = description;
       this.author = author;
       this.infoLink = infoLink;
       this.boxLink = boxLink;
       this.pageLink = pageLink;
       this.registeredOn = registeredOn;
       this.iconLink = iconLink;
       this.owner = owner;
       this.enabled = enabled;
       this.configPage = configPage;
       this.privateKey = privateKey;
       this.apiGadgetHasUsers = apiGadgetHasUsers;
       this.apiGadgetHasPermissions = apiGadgetHasPermissions;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }

    @Column(name="title", nullable=false)
		public String getTitle() {
			return this.title;
		}

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name="description", length=65535)
		public String getDescription() {
			return this.description;
		}

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="author")
		public String getAuthor() {
			return this.author;
		}

    public void setAuthor(String author) {
        this.author = author;
    }

    @Column(name="info_link")
		public String getInfoLink() {
			return this.infoLink;
		}

    public void setInfoLink(String infoLink) {
        this.infoLink = infoLink;
    }

    @Column(name="box_link", nullable=false)
		public String getBoxLink() {
			return this.boxLink;
		}

    public void setBoxLink(String boxLink) {
        this.boxLink = boxLink;
    }

    @Column(name="page_link")
		public String getPageLink() {
			return this.pageLink;
		}

    public void setPageLink(String pageLink) {
        this.pageLink = pageLink;
    }

    @Column(name="registered_on", nullable=false)
		public long getRegisteredOn() {
			return this.registeredOn;
		}

    public void setRegisteredOn(long registeredOn) {
        this.registeredOn = registeredOn;
    }

    @Column(name="icon_link")
		public String getIconLink() {
			return this.iconLink;
		}

    public void setIconLink(String iconLink) {
        this.iconLink = iconLink;
    }

    @Column(name="owner", nullable=false)
		public String getOwner() {
			return this.owner;
		}

    public void setOwner(String owner) {
        this.owner = owner;
    }

    @Column(name="enabled", nullable=false)
		public boolean isEnabled() {
			return this.enabled;
		}

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    @Column(name="config_page")
		public String getConfigPage() {
			return this.configPage;
		}

    public void setConfigPage(String configPage) {
        this.configPage = configPage;
    }

    @Column(name="private_key", nullable=false, length=36)
		public String getPrivateKey() {
			return this.privateKey;
		}

    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="gadget")
		public Set<ApiGadgetHasUser> getApiGadgetHasUsers() {
			return this.apiGadgetHasUsers;
		}

    public void setApiGadgetHasUsers(Set<ApiGadgetHasUser> apiGadgetHasUsers) {
        this.apiGadgetHasUsers = apiGadgetHasUsers;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="gadget")
		public Set<ApiGadgetHasPermission> getApiGadgetHasPermissions() {
			return this.apiGadgetHasPermissions;
		}

    public void setApiGadgetHasPermissions(Set<ApiGadgetHasPermission> apiGadgetHasPermissions) {
        this.apiGadgetHasPermissions = apiGadgetHasPermissions;
    }




}


