angular
	.module("formsManagerApp")
	.constant("SERVICES", {
		_PREFIX: "/api/apps/forms"
		_WD_PREFIX: "/api/qbe"
		PROJECTS: "/projects"
		RECENT_PROJECTS: "/projects/recent"
		FORM_RESOURCES: "/resources"
		FORM: "/forms"
		FORM_VERSION: "/form-versions"
		FORM_VERSIONS: "/versions"
		FORM_VERSIONS_LOCKED_COUNT: "/versions/countLockedByOtherUser"
		FORM_VERSION_LOCK: "/lock"
		FORM_VERSION_UNLOCK: "/unlock"
		FORM_VERSION_CAN_FINALISE: "/canFinalise"
		FORM_VERSION_FINALISE: "/finalise"
		FORM_VERSION_ENABLE_TESTING: "/enableTesting"
		FORM_VERSION_DISABLE_TESTING: "/disableTesting"
		FORM_VERSION_EXPORT: "/export"
		FORM_VERSION_IMPORT: "/import-version"
		WORKING_SETS: "/working-sets"
		RULES: "/rules"
		LANGUAGES: "/i18n/languages"
		CONDITION_TYPES: "/condition-types"
		CATEGORY: "/categories"
		CATEGORY_RESOURCES_COUNT: "/resources/count"
		_SORT_RECENT_PROJECTS: "lastAccessedOn"
		_ORDER_RECENT_PROJECTS: "desc"
		_START_RECENT_PROJECTS: "0"
		_SIZE_RECENT_PROJECTS: "4"

		CONFIG: "/config"
		CONFIG_OPERATIONS: "/operations"
		CONFIG_USERS: "/users"
		CONFIG_GROUPS: "/groups"
		CONFIG_DOMAINS: "/domains"
		CONFIG_MANAGED_USERS: "/users/managed"
		CONFIG_MANAGED_GROUPS: "/groups/managed"
		CONFIG_SUBJECTS: "/subjects"
	})
