/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.wiki.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WikEntryVersion generated by hbm2java
 */
@Entity
@Table(name="wik_entry_version"
)
public class WikEntryVersion  implements java.io.Serializable {


     private String id;
     private WikEntry wikEntryId;
     private int entryVersion;
     private String createdBy;
     private long dtCreated;
     private String comment;
     private String pageContent;

    public WikEntryVersion() {
    }

    public WikEntryVersion(WikEntry wikEntryId, int entryVersion, String createdBy, long dtCreated, String comment) {
       this.wikEntryId = wikEntryId;
       this.entryVersion = entryVersion;
       this.createdBy = createdBy;
       this.dtCreated = dtCreated;
       this.comment = comment;
    }

    public WikEntryVersion(WikEntry wikEntryId, int entryVersion, String createdBy, long dtCreated, String comment, String pageContent) {
        this.wikEntryId = wikEntryId;
        this.entryVersion = entryVersion;
        this.createdBy = createdBy;
        this.dtCreated = dtCreated;
        this.comment = comment;
        this.pageContent = pageContent;
     }
    
		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wik_entry_id", nullable=false)
		public WikEntry getWikEntryId() {
			return this.wikEntryId;
		}

    public void setWikEntryId(WikEntry wikEntryId) {
        this.wikEntryId = wikEntryId;
    }

    @Column(name="entry_version", nullable=false)
		public int getEntryVersion() {
			return this.entryVersion;
		}

    public void setEntryVersion(int entryVersion) {
        this.entryVersion = entryVersion;
    }

    @Column(name="created_by", nullable=false, length=36)
		public String getCreatedBy() {
			return this.createdBy;
		}

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name="dt_created", nullable=false)
		public long getDtCreated() {
			return this.dtCreated;
		}

    public void setDtCreated(long dtCreated) {
        this.dtCreated = dtCreated;
    }

    @Column(name="comment", nullable=false)
		public String getComment() {
			return this.comment;
		}

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name="page_content", length=65535)
		public String getPageContent() {
			return this.pageContent;
		}

    public void setPageContent(String pageContent) {
        this.pageContent = pageContent;
    }

}


