/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.wiki.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WikEntryHasTag generated by hbm2java
 */
@Entity
@Table(name="wik_entry_has_tag"
    , uniqueConstraints = @UniqueConstraint(columnNames={"wik_entry_id", "wik_tag_id"})
)
public class WikEntryHasTag  implements java.io.Serializable {


     private String id;
     private WikTag wikTagId;
     private WikEntry wikEntryId;

    public WikEntryHasTag() {
    }

    public WikEntryHasTag(WikTag wikTagId, WikEntry wikEntryId) {
       this.wikTagId = wikTagId;
       this.wikEntryId = wikEntryId;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wik_tag_id", nullable=false)
		public WikTag getWikTagId() {
			return this.wikTagId;
		}

    public void setWikTagId(WikTag wikTagId) {
        this.wikTagId = wikTagId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wik_entry_id", nullable=false)
		public WikEntry getWikEntryId() {
			return this.wikEntryId;
		}

    public void setWikEntryId(WikEntry wikEntryId) {
        this.wikEntryId = wikEntryId;
    }




}


