/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.wiki.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WikTag generated by hbm2java
 */
@Entity
@Table(name="wik_tag"
    , uniqueConstraints = @UniqueConstraint(columnNames="name")
)
public class WikTag  implements java.io.Serializable {


     private String id;
     private String name;
     private String description;
     private Set<WikEntryHasTag> wikEntryHasTags = new HashSet<WikEntryHasTag>(0);

    public WikTag() {
    }


    public WikTag(String name) {
        this.name = name;
    }
    public WikTag(String name, String description, Set<WikEntryHasTag> wikEntryHasTags) {
       this.name = name;
       this.description = description;
       this.wikEntryHasTags = wikEntryHasTags;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }

    @Column(name="name", unique=true, nullable=false, length=45)
		public String getName() {
			return this.name;
		}

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="description", length=45)
		public String getDescription() {
			return this.description;
		}

    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="wikTagId")
		public Set<WikEntryHasTag> getWikEntryHasTags() {
			return this.wikEntryHasTags;
		}

    public void setWikEntryHasTags(Set<WikEntryHasTag> wikEntryHasTags) {
        this.wikEntryHasTags = wikEntryHasTags;
    }




}


