/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.wiki.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WikWiki generated by hbm2java
 */
@Entity
@Table(name="wik_wiki"
    , uniqueConstraints = @UniqueConstraint(columnNames="name")
)
public class WikWiki  implements java.io.Serializable {


     private String id;
     private String name;
     private String description;
     private byte[] logo;
     private Set<WikEntry> wikEntries = new HashSet<WikEntry>(0);

    public WikWiki() {
    }


    public WikWiki(String name) {
        this.name = name;
    }
    public WikWiki(String name, String description, byte[] logo, Set<WikEntry> wikEntries) {
       this.name = name;
       this.description = description;
       this.logo = logo;
       this.wikEntries = wikEntries;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }

    @Column(name="name", unique=true, nullable=false, length=45)
		public String getName() {
			return this.name;
		}

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="description", length=1000)
		public String getDescription() {
			return this.description;
		}

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="logo")
		public byte[] getLogo() {
			return this.logo;
		}

    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="wikiId")
		public Set<WikEntry> getWikEntries() {
			return this.wikEntries;
		}

    public void setWikEntries(Set<WikEntry> wikEntries) {
        this.wikEntries = wikEntries;
    }




}


