/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.clipboard.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClbMetadata generated by hbm2java
 */
@Entity
@Table(name="clb_metadata"
)
public class ClbMetadata  implements java.io.Serializable {


     private String id;
     private ClbEntry clbContentId;
     private String metaName;
     private String metaValue;

    public ClbMetadata() {
    }

    public ClbMetadata(ClbEntry clbContentId, String metaName, String metaValue) {
       this.clbContentId = clbContentId;
       this.metaName = metaName;
       this.metaValue = metaValue;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clb_content_id", nullable=false)
		public ClbEntry getClbContentId() {
			return this.clbContentId;
		}

    public void setClbContentId(ClbEntry clbContentId) {
        this.clbContentId = clbContentId;
    }

    @Column(name="meta_name", nullable=false)
		public String getMetaName() {
			return this.metaName;
		}

    public void setMetaName(String metaName) {
        this.metaName = metaName;
    }

    @Column(name="meta_value", nullable=false)
		public String getMetaValue() {
			return this.metaValue;
		}

    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }




}


