/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.forum.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FrmAttachment generated by hbm2java
 */
@Entity
@Table(name="frm_attachment"
)
public class FrmAttachment  implements java.io.Serializable {


     private String id;
     private FrmMessage frmMessageId;
     private byte[] content;
     private String filename;
     private String mimetype;

    public FrmAttachment() {
    }

    public FrmAttachment(FrmMessage frmMessageId, byte[] content, String filename, String mimetype) {
       this.frmMessageId = frmMessageId;
       this.content = content;
       this.filename = filename;
       this.mimetype = mimetype;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="frm_message_id", nullable=false)
		public FrmMessage getFrmMessageId() {
			return this.frmMessageId;
		}

    public void setFrmMessageId(FrmMessage frmMessageId) {
        this.frmMessageId = frmMessageId;
    }

    @Column(name="content", nullable=false)
		public byte[] getContent() {
			return this.content;
		}

    public void setContent(byte[] content) {
        this.content = content;
    }

    @Column(name="filename", nullable=false)
		public String getFilename() {
			return this.filename;
		}

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Column(name="mimetype", nullable=false)
		public String getMimetype() {
			return this.mimetype;
		}

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }




}


