/*
* Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
*
* Licensed under the EUPL, Version 1.1 only (the "License").
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*/
package com.eurodyn.qlack2.fuse.forum.impl.model;
// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FrmTopic generated by hbm2java
 */
@Entity
@Table(name="frm_topic"
)
public class FrmTopic  implements java.io.Serializable {


     private String id;
     private FrmForum frmForumId;
     private String title;
     private String description;
     private byte[] logo;
     private long createdOn;
     private short status;
     private String createdBy;
     private boolean moderated;
     private boolean archived;
     private short moderationStatus;
     private Set<FrmMessage> frmMessages = new HashSet<FrmMessage>(0);

    public FrmTopic() {
    }


    public FrmTopic(FrmForum frmForumId, String title, long createdOn, short status, String createdBy, boolean moderated, boolean archived, short moderationStatus) {
        this.frmForumId = frmForumId;
        this.title = title;
        this.createdOn = createdOn;
        this.status = status;
        this.createdBy = createdBy;
        this.moderated = moderated;
        this.archived = archived;
        this.moderationStatus = moderationStatus;
    }
    public FrmTopic(FrmForum frmForumId, String title, String description, byte[] logo, long createdOn, short status, String createdBy, boolean moderated, boolean archived, short moderationStatus, Set<FrmMessage> frmMessages) {
       this.frmForumId = frmForumId;
       this.title = title;
       this.description = description;
       this.logo = logo;
       this.createdOn = createdOn;
       this.status = status;
       this.createdBy = createdBy;
       this.moderated = moderated;
       this.archived = archived;
       this.moderationStatus = moderationStatus;
       this.frmMessages = frmMessages;
    }

		@Id
		public String getId() {
		if (this.id == null) {
             this.id = java.util.UUID.randomUUID().toString();
         }

		 return this.id;
		}

    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="frm_forum_id", nullable=false)
		public FrmForum getFrmForumId() {
			return this.frmForumId;
		}

    public void setFrmForumId(FrmForum frmForumId) {
        this.frmForumId = frmForumId;
    }

    @Column(name="title", nullable=false, length=254)
		public String getTitle() {
			return this.title;
		}

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name="description", length=1000)
		public String getDescription() {
			return this.description;
		}

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="logo")
		public byte[] getLogo() {
			return this.logo;
		}

    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

    @Column(name="created_on", nullable=false)
		public long getCreatedOn() {
			return this.createdOn;
		}

    public void setCreatedOn(long createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name="status", nullable=false)
		public short getStatus() {
			return this.status;
		}

    public void setStatus(short status) {
        this.status = status;
    }

    @Column(name="created_by", nullable=false, length=36)
		public String getCreatedBy() {
			return this.createdBy;
		}

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name="moderated", nullable=false)
		public boolean isModerated() {
			return this.moderated;
		}

    public void setModerated(boolean moderated) {
        this.moderated = moderated;
    }

    @Column(name="archived", nullable=false)
		public boolean isArchived() {
			return this.archived;
		}

    public void setArchived(boolean archived) {
        this.archived = archived;
    }

    @Column(name="moderation_status", nullable=false)
		public short getModerationStatus() {
			return this.moderationStatus;
		}

    public void setModerationStatus(short moderationStatus) {
        this.moderationStatus = moderationStatus;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="frmTopicId")
		public Set<FrmMessage> getFrmMessages() {
			return this.frmMessages;
		}

    public void setFrmMessages(Set<FrmMessage> frmMessages) {
        this.frmMessages = frmMessages;
    }




}


